package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"errors"
	"fmt"
	"graphql-example/graph/model"
	"graphql-example/repository"
	"strings"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.CreateTaskPayload, error) {
	task, err := r.Repo.CreateTask(ctx, input.Title, input.Description, input.CategoryID, input.Deadline)
	if err != nil {
		return nil, err
	}
	return &model.CreateTaskPayload{Task: task}, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.UpdateTaskPayload, error) {
	task, err := r.Repo.UpdateTask(ctx, id, input.Title, input.Description, input.CategoryID, input.Status.String(), input.Deadline)
	if err != nil {
		if errors.Is(err, repository.ErrTaskNotFound) {
			return &model.UpdateTaskPayload{
				Errors: []model.Error{model.NotFoundError{Message: fmt.Sprintf("ID:%s not found", id)}},
			}, nil
		}
		return nil, err
	}
	return &model.UpdateTaskPayload{Task: task}, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (*model.DeleteTaskPayload, error) {
	err := r.Repo.DeleteTask(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrTaskNotFound) {
			return &model.DeleteTaskPayload{
				Errors: []model.Error{model.NotFoundError{Message: fmt.Sprintf("ID:%s not found", id)}},
			}, nil
		}
		return nil, err
	}
	return &model.DeleteTaskPayload{ID: id}, nil
}

// AddCategory is the resolver for the addCategory field.
func (r *mutationResolver) AddCategory(ctx context.Context, input model.AddCategoryInput) (*model.AddCategoryPayload, error) {
	category, err := r.Repo.AddCategory(ctx, input.Name)
	if err != nil {
		return nil, err
	}
	return &model.AddCategoryPayload{Category: category}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategoryInput) (*model.UpdateCategoryPayload, error) {
	category, err := r.Repo.UpdateCategory(ctx, id, input.Name)
	if err != nil {
		if errors.Is(err, repository.ErrCategoryNotFound) {
			return &model.UpdateCategoryPayload{
				Errors: []model.Error{model.NotFoundError{Message: fmt.Sprintf("ID:%s not found", id)}},
			}, nil
		}
		return nil, err
	}
	return &model.UpdateCategoryPayload{Category: category}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (*model.DeleteCategoryPayload, error) {
	err := r.Repo.DeleteCategory(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrCategoryNotFound) {
			return &model.DeleteCategoryPayload{
				Errors: []model.Error{model.NotFoundError{Message: fmt.Sprintf("ID:%s not found", id)}},
			}, nil
		}
		return nil, err
	}
	return &model.DeleteCategoryPayload{ID: id}, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.Repo.GetAllTask(ctx)
	if err != nil {
		return nil, err
	}
	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.Repo.GetTaskById(ctx, id)
	if err != nil {
		return nil, err
	}
	return task, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categories, err := r.Repo.GetAllCategory(ctx)
	if err != nil {
		return nil, err
	}
	return categories, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	parts := strings.Split(id, "_")

	// 先頭の要素がv1部分、2番目の要素がCategoryになる
	_, nType := parts[0], parts[1]

	switch nType {
	case "Task":
		return r.Repo.GetTaskById(ctx, id)
	case "Category":
		return r.Repo.GetCategoryById(ctx, id)
	default:
		return nil, errors.New("invalid ID")
	}
}

// Category is the resolver for the category field.
func (r *taskResolver) Category(ctx context.Context, obj *model.Task) (*model.Category, error) {
	return r.Repo.GetCategoryById(ctx, obj.Category.ID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type taskResolver struct{ *Resolver }
